name: Deploy Airflow DAGs

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  airflow-dags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ vars.PROD_WI_PROVIDER_NAME }}
          service_account: ${{ vars.PROD_SA_EMAIL }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'sync DAG files'
        run: 'gsutil -m rsync -d -r airflow-composer/dags <tbd>'
